filebeat.inputs:
  - type: filestream
    id: default-filestream
    paths:
      - /usr/share/filebeat/logs/*.log

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"


filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true


processors:
  - add_docker_metadata: ~


setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}


output.elasticsearch:
  index: "filebeat-%{+yyyy.MM.dd}"
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: "/usr/share/filebeat/certs/ca/ca.crt"
  ssl.certificate: "/usr/share/filebeat/certs/es01/es01.crt"
  ssl.key: "/usr/share/filebeat/certs/es01/es01.key"
